logging:
  path: logback-spring.xml

server: 
  port: 8080
  connection-timeout:
    60000
    
  
spring:
  datasource:
    url: jdbc:mysql://120.77.153.124:3306/data_manage?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    #初始化大小，最小，最大
    initialSize: 8
    minIdle: 8
    maxActive: 100
    #获取连接等待超时时间
    maxWait: 1000
    testOnBorrow: true
    validationQuery: select 1 
    #打开PSCache，并且指定每一个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能； 慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240000
  http:
    encoding:
      enabled: true
      charset: utf-8
      
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-idle: 1000
        max-active: 10000
        min-idle: 0
        max-wait: 60000
    database: 0
    
  devtools:
    restart:
      enabled: true
      
  rabbitmq:
    addresses: 127.0.0.1:5672
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
      
mybatis:
  mapper-locations: classpath:mapper/*.xml

          